Changed directory to /rds/user/mrn31/hpc-work/euler/runs.

JobID: 55250426
======
Time: Sun 13 Feb 16:51:07 GMT 2022
Running on master node: cpu-p-514
Current directory: /rds/user/mrn31/hpc-work/euler/runs

Nodes allocated:
================
cpu-p-514

numtasks=32, numnodes=1, mpi_tasks_per_node=32 (OMP_NUM_THREADS=1)

Executing command:
==================
mpirun -ppn 32 -np 32  

/home/mrn31/.conda/envs/kwant/lib/python3.8/site-packages/kwant/solvers/default.py:16: RuntimeWarning: MUMPS is not available, SciPy built-in solver will be used as a fallback. Performance can be very poor in this case.
  warnings.warn("MUMPS is not available, "
Traceback (most recent call last):
  File "./parallel_dis_kag_Gaus_2.py", line 331, in <module>
    main()
  File "./parallel_dis_kag_Gaus_2.py", line 322, in main
    for result in results:
  File "/home/mrn31/.conda/envs/kwant/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/mrn31/.conda/envs/kwant/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/home/mrn31/.conda/envs/kwant/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/mrn31/.conda/envs/kwant/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
slurmstepd: error: Detected 12329 oom-kill event(s) in step 55250426.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
